SELECT * FROM USER_AUTHORITY;
SELECT * FROM AUTHORITY;
SELECT * FROM USER ;

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (1, 'ROLE_USER');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (1, 'ROLE_ADMIN');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (2, 'ROLE_USER');

DROP TABLE USER_AUTHORITY;
DROP TABLE AUTHORITY;
DROP TABLE USER ;

DELETE FROM USER_AUTHORITY WHERE USER_ID = '35';
DELETE FROM USER WHERE USER_ID = '35';